name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      vname:
        description: 'Version name'     
        required: true
        default: 'v0.1.0'
      prerelease:
        description: 'Pre-release'
        required: false
        type: boolean
        default: false
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Runs a single command using the runners shell
      - name: Install PyInstaller
        run: pip install pyinstaller

      # Runs a set of commands using the runners shell
      - name: Compile code
        run: pyinstaller --onefile .\main.py
      
      - name: Upload files to github release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: ./dist/main
          tag: ${{ github.event.inputs.vname }}
          prerelease: ${{ github.event.inputs.prerelease }}
          asset_name: pseudocode.exe

